### ISSUE TITLE
Nova theme for Kitty

### ISSUE THREAD

**Issue by megalithic** [trevordmiller/nova-vim#100]
@trevordmiller I'm fiddling with different terminals right now, and am trying [Kitty](https://github.com/kovidgoyal/kitty) so figured I'd send  you the Nova color scheme for it too: 

```
# Nova Theme
background #3C4C55
foreground #C5D4DD
cursor #C0C5CE
#black
color0 #3C4C55
color8 #899BA6
# red
color1 #DF8C8C
color9 #F2C38F
# green
color2 #A8CE93
color10 #A8CE93
# yellow
color3 #DADA93
color11 #DADA93
# blue
color4 #83AFE5
color12 #83AFE5
# magenta
color5 #9A93E1
color13 #D18EC2
# cyan
color6 #7FC1CA
color14 #7FC1CA
# white
color7 #C5D4DD
color15 #E6EEF3

```

**Comment by trevordmiller** [comment]
@megalithic Awesome! If you want to create a repo with a build step using the `nova-colors` package, I'll happily add this to [the Nova website](https://trevordmiller.com/projects/nova). Here are some examples:

- [nova-iterm](https://github.com/trevordmiller/nova-iterm)
- [nova-gnome-terminal](https://github.com/agarrharr/nova-gnome-terminal)
