### ISSUE TITLE
Please, add support for PHP

### ISSUE THREAD

**Issue by alexdrupal** [trevordmiller/nova-vim#104]
![php_colors](https://user-images.githubusercontent.com/38625/44341457-9a8d5680-a490-11e8-91aa-be44aafdfed3.png)

**Comment by trevordmiller** [comment]
Hey @alexdrupal! Thanks for reaching out. PHP is not a priority language for me, but feel free to submit a pull request if you'd like :) Here are the contributing instructions if you are interested: https://github.com/trevordmiller/nova-vim/blob/master/contributing.md
