### ISSUE TITLE
Doesn't support tabs using `airline`

### ISSUE THREAD

**Issue by bigH** [trevordmiller/nova-vim#108]
My config looks like:
```
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffers_label = ''
let g:airline#extensions#tabline#tabs_label = ''
```

All the tab colors are identical so it's impossible to know what's highlighted and what's not.

**Comment by trevordmiller** [comment]
I don’t use airline myself but would accept a pull request if you or someone else would like to :) See the `contributing.md` if interested. I’m going to close this for now but if I get a pull request for it I’ll reopen.
