### ISSUE TITLE
Neovim floating window colors support

### ISSUE THREAD

**Issue by fannheyward** [trevordmiller/nova-vim#111]
Neovim has add floating window feature, and the highlight in floating window is broken:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/345274/54504452-ada4ce00-496e-11e9-95de-c459b12ccf09.png">

**Comment by trevordmiller** [comment]
I don’t use or support neovim myself but PRs are welcome following the contributing.md :) Closing this for now but will reopen if a PR is submitted for this.

**Comment by trevordmiller** [comment]
This was released in https://github.com/trevordmiller/nova-vim/releases/tag/v3.22.1 thanks to @DodoMomo
