### ISSUE TITLE
Colors in Neovim terminal mode

### ISSUE THREAD

**Issue by aharris88** [trevordmiller/nova-vim#15]
When I run terminal mode inside of neovim (`:terminal`), the colors on my prompt are incorrect compared to the way they are in the normal terminal.

In this image, the top part is a tmux pane with neovim in terminal mode and the bottom is just my normal terminal (zsh with [pure prompt](https://github.com/sindresorhus/pure)).

![screen shot 2016-09-21 at 12 18 05 pm](https://cloud.githubusercontent.com/assets/3266363/18723394/9442ee00-7ff5-11e6-89b2-d9a6d11274be.png)

Here are some issues describing the problem and how to fix it.

https://github.com/neovim/neovim/issues/2897

https://github.com/neovim/neovim/issues/4696

**Comment by trevordmiller** [comment]
Hey @spicydonuts, is this the same issue you are experiencing?

**Comment by trevordmiller** [comment]
I can add these values to map to `nova-colors` values in `colors/nova.vim`

**Comment by trevordmiller** [comment]
Hey @aharris88 and @spicydonuts, do you mind updating to `2.2.3` and confirming if this solved the problem?

**Comment by spicydonuts** [comment]
Fixed!  Thank you!

**Comment by aharris88** [comment]
Yeah, looks good!

**Comment by trevordmiller** [comment]
yay! Thanks for testing.
