### ISSUE TITLE
Add colors for Airline

### ISSUE THREAD

**Issue by alexlafroscia** [trevordmiller/nova-vim#21]
A lot of Vim users use [vim-airline](https://github.com/vim-airline/vim-airline), and having theme support there would be awesome!  For example, the Gruvbox theme does a nice job of providing an [Airline config file](https://github.com/morhetz/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim).  Right now, it looks like this, which is not a great experience:

![screen shot 2016-09-26 at 3 36 53 pm](https://cloud.githubusercontent.com/assets/1645881/18854277/0eab55d0-83ff-11e6-9f08-05dc2d0f7ca8.png)

**Comment by trevordmiller** [comment]
Thanks for the feedback! I agree. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)

**Comment by alexlafroscia** [comment]
Cool! I'll mess with this tonight and see if I can get one generated automatically, but I'm not sure what colors should go where... If I can do some of the leg work though, I'll do that and you can figure out the colors.

**Comment by trevordmiller** [comment]
Thanks @alexlafroscia! That would be great. Check out the nova-vim source code to see how the "nova-colors" values are used and built; as far as color picking I'm happy to help out - I use the Nova color meanings; for the airline theme, I would assume color use will be one of three options: everything is a "decoration" shade of gray except current state (novaColors.normal.cyan for things that show user state like current like and column number) and user action required (novaColors.normal.red for things that require user action like errors). Let me know if you need any help!

**Comment by alnjxn** [comment]
I put together a really simple lightline theme using estilo. If you guys settle on the color config for airline i'd be happy to update to match and contribute back to this project. https://github.com/alnjxn/estilo-nova

**Comment by trevordmiller** [comment]
@alnjxn Cool, thanks for letting us know! I believe @alexlafroscia has the colors set in stone in this pull request: https://github.com/trevordmiller/nova-vim/pull/22. Feel free to update to match. That pull request just has one final change and then I'll be merging it in.
