### ISSUE TITLE
Text color in folds is too dark

### ISSUE THREAD

**Issue by alexlafroscia** [trevordmiller/nova-vim#23]
Not sure if it's just me, but having the text darker than the fold color makes it _really_ hard to read

<img width="352" alt="screen shot 2016-09-27 at 10 47 49 pm" src="https://cloud.githubusercontent.com/assets/1645881/18902012/7db9f462-8504-11e6-9fa3-75bf44866e5a.png">

I think a lighter color would make it much more legible.

**Comment by trevordmiller** [comment]
I agree. I'll take care of this. Thanks for the feedback.

**Comment by trevordmiller** [comment]
@alexlafroscia I pushed a fix for this:
![screen shot 2016-09-28 at 4 51 48 pm](https://cloud.githubusercontent.com/assets/5497885/18935361/ba491398-859c-11e6-855b-f669f3fdcd30.png)
![screen shot 2016-09-28 at 4 51 22 pm](https://cloud.githubusercontent.com/assets/5497885/18935360/ba452f80-859c-11e6-84c4-f1298448d984.png)


I updated both folds and fold columns (if enabled) to be `normal.cyan` (the Nova color which represents user state) which in term makes them much more readable; this is how it should have been built originally but I made a mistake and don't use folds so I missed this. Thank you for letting me know!

**Comment by alexlafroscia** [comment]
Awesome, thanks @trevordmiller!
