### ISSUE TITLE
Clean up plugin rules

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova-vim#32]
Place the "Plugins" section rules in the related color mapping groups so the plugins section can be removed and all rules are organized by semantics.
From https://github.com/trevordmiller/nova-vim/pull/31

**Comment by kumarmj** [comment]
I will be happy to work on this, please let me know what do you mean by 
> related color mapping groups

**Comment by trevordmiller** [comment]
@kumarmj Sounds great, thank you for your interest! The "Plugins" section is out of place since all other rules are organized by purpose. So, the only change that needs to be made is to rename the ["PLUGINS" header comment](https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L238) to be "VERSION CONTROL"; after you change the text in that comment, you can just run `npm run push -- patch` and submit a pull request and you're good to go!

**Comment by trevordmiller** [comment]
@kumarmj This will help the color mappings (meaning the mappings from each highlight group to the related color variable) to match the `nova-colors` groups: https://github.com/trevordmiller/nova-colors/blob/master/src/index.js
