### ISSUE TITLE
Add better support for git views

### ISSUE THREAD

**Issue by alexlafroscia** [trevordmiller/nova-vim#38]
I've noticed that some improvements could be made to some of the Git-related colors with this theme.

For example, if you're diffing two files, seeing the changes in red/green might be helpful.  Instead, I'm getting this:

<img width="835" alt="screen shot 2016-10-11 at 11 15 31 am" src="https://cloud.githubusercontent.com/assets/1645881/19282646/0d385a6c-8fa4-11e6-8806-006245990509.png">

Compare to the coloring of Gruvbox, which makes it super obvious what's added/removed/changed.

<img width="826" alt="screen shot 2016-10-11 at 11 14 59 am" src="https://cloud.githubusercontent.com/assets/1645881/19282653/167b39dc-8fa4-11e6-9b98-2654881b8659.png">

What do you think about setting the background color of the added lines to green instead of blue, and maybe doing something different with changed lines to highlight them as well?

**Comment by trevordmiller** [comment]
@alexlafroscia Great idea! I agree. Along with using background colors, it would be good to update to use the [`nova-colors` `versionControlGroups`](https://github.com/trevordmiller/nova-colors/blob/master/src/index.js#L45-L50); right now git related highlight groups are incorrectly not using `versionControlGroups`. Would you mind taking this one? If not, I'll get to it :)

**Comment by alexlafroscia** [comment]
Sure, I'll add it to my list and see if I can get to it tonight.

**Comment by trevordmiller** [comment]
Thanks @alexlafroscia you rock. If you don't have time no worries I'll take care of it at some point :)

**Comment by alexlafroscia** [comment]
@trevordmiller Add/removed is pretty easy, but changed lines vs. the actual part of the line that changes (blue background vs. yellow background in the Gruvbox screenshot) are two different color groups.  How do you want me to handle that?

**Comment by trevordmiller** [comment]
@alexlafroscia Would it make sense to use `novaColors.versionControlGroups.modified` (orange) for the line that changes and `novaColors.versionControlGroups.renamed` (blue) for the actual part of the line that changed? Or we could extend `nova-colors` with `versionControlGroups.exactModified` (and set it equal to one of the unused `colorValues` for `versionControlGroups`) or something? I'll defer to whatever you think is best as I don't use vim diffs (I use terminal git outside of vim for git stuff).

**Comment by alexlafroscia** [comment]
> Would it make sense to use novaColors.versionControlGroups.modified (orange) for the line that changes and novaColors.versionControlGroups.renamed (blue) for the actual part of the line that changed?

I like this idea.  It looks something like this:

<img width="788" alt="screen shot 2016-10-12 at 10 11 08 am" src="https://cloud.githubusercontent.com/assets/1645881/19319968/3f2344cc-9064-11e6-9bde-e300c26cbc98.png">

The blue text on orange background is too light IMO.  We could always change the background color behind that text through.

**Comment by alexlafroscia** [comment]
A darker orange color for the changed text might look nice

**Comment by trevordmiller** [comment]
@alexlafroscia Thanks for looking at that. Yeah if you can use the background color with the blue (`versionControlGroups.renamed`) that would be best as I would prefer not to extend `nova-colors` unless absolutely necessary. You could also experiment with passing in `underline` so that the inline change is the same color as the line but is underlined or something; that would require re-working how the highlight helper works to allow passing in style modifiers. Without actually trying it out, I would imagine just doing what you did with the blue but making it the background instead of the foreground would probably work best.

**Comment by alexlafroscia** [comment]
alright, so I'll try

- Blue background
- Orange text
- Underline (maybe)

Right?

**Comment by trevordmiller** [comment]
@alexlafroscia Sure, whatever you think makes the most sense :)
