### ISSUE TITLE
Start script errors

### ISSUE THREAD

**Issue by alexlafroscia** [trevordmiller/nova-vim#40]
The start script isn't working for me.  I keep getting the following error:

> ln: /Users/alexlafroscia/.vim/colors/nova.vim: No such file or directory

**Comment by trevordmiller** [comment]
@alexlafroscia Do you have a `.vim/colors` directory? I thought that comes default with Vim, but if the `colors` directory is absent you will need to `mkdir ~/.vim/colors/` for that error to go away so it can place `nova.vim` inside it. If this is the problem, we could update the `start` script to create this directory if it doesn't exist.

**Comment by alexlafroscia** [comment]
I'm a Neovim user so my config directory is `.config/nvim`, but I don't have a `colors` directory there either.  After actually using this start script, I wish I had the old one 😝 I already use my locally cloned version using `vim-plug` so the old start script's behavior and the new one would be the same, except this symlink issue means I have to run `npm run build` manually every time I change stuff now.

**Comment by trevordmiller** [comment]
@alexlafroscia Bummer, yeah I looked into it and the `colors` dir thing is specific to Vim, so do you mind just pulling that out of the `start` script so it is like it was before? Sorry about that!

**Comment by alexlafroscia** [comment]
Sure, I can do that

**Comment by trevordmiller** [comment]
Another Neovim user wanted to contribute and ran into the same issue: https://github.com/trevordmiller/nova-vim/issues/42

So I vote we take this out and instead add a `CONTRIBUTING.md` with info on how to symlink for both Vim and Neovim to test changes locally before pushing.

**Comment by trevordmiller** [comment]
I'm happy to take care of this if nobody else wants to

**Comment by alexlafroscia** [comment]
Yeah, I think that's a good idea. I also just ran into the fact that the push script fails because of the symlink as well.

**Comment by trevordmiller** [comment]
Sounds good I'll take care of this.
