### ISSUE TITLE
Avoid needing to tag a version as part of a pull request

### ISSUE THREAD

**Issue by alexlafroscia** [trevordmiller/nova-vim#44]
I've run into problems around having the tag as part of the PR when you often rebase commits to make amends.  It seems like Travis CI should be able to do that step in the `deploy` hook after a successful merge into `master`.

http://stackoverflow.com/a/28230711/2250435

In addition, this doesn't play that nicely when you have multiple PRs open at the same time.

***

One challenge to address would be the fact that it might be hard to programmatically determine whether to make the change a major/minor/patch update.  Is there a reason that that is relevant?  Something like a colorscheme I wouldn't expect to follow proper semver, since it's not like it will be a dependency of anything where that metadata is relevant.

What's the reason for needing to tag every change?  Some of the package managers require that?  I only use `vim-plug` and AFAIK it just monitors a remote branch and updates with any changes.

**Comment by alexlafroscia** [comment]
Related comments:

https://github.com/trevordmiller/nova-vim/pull/41#issuecomment-253657242
https://github.com/trevordmiller/nova-vim/pull/43#issuecomment-253657400

**Comment by trevordmiller** [comment]
@alexlafroscia I agree. I'll probably add [`semantic-release`](https://github.com/semantic-release/semantic-release) to tag after CI succeeds; this does unfortunately add a requirement to have specific commit messages (so you know what type of change it is - major, minor, or patch - for semver). What do you think? Probably better than running `npm version` (via `push` script) locally.

**Comment by alexlafroscia** [comment]
Hmm, that's interesting. I had seen it but never really dug into trying it out. Seems like a really interesting option though, and I generally love the idea of commit messages having a particular format.  I think it's important that commits include the details on the what and why of the changes, and driving the version change from that data is a cool idea.

**Comment by trevordmiller** [comment]
Yeah I'm willing to try it out; I've made a few packages (which rely on semver + versioning) and haven't found a great solution to follow semver but still have easy contributing and PRs. I'll add this in when I have some time and we can try it out and see what we think :)

**Comment by alexlafroscia** [comment]
Yeah, it's always tough. I find it fascinating that the Elm language can actually do it automatically by looking at your code and determining if anything changed! Pretty amazing, but poor old JavaScript will probably never see anything like that 😝

**Comment by trevordmiller** [comment]
I did some more research and it doesn't see that `semantic-release` is a good option for a few reasons:

0. it auto-publishes the package to npm after CI success (which this Vim plugin doesn't need, its only on GitHub)
0. it forces a pretty prescriptive setup that I feel is even more of a burden than manual tagging and resolving conflicts on multiple PRs
0. It has a lot of unresolved issues on GitHub, seems like it creates more problems than it solves

Unless there is another, slimmer alternative to `semantic-release`, I feel the best options are to either

0. continue to have contributors own manual tagging or
0. remove deploy from CI and have the repo admin (myself) version and deploy after each pull request is merged

What do you think @alexlafroscia? Do you know if there is a better option that package authors  (both on and off npm) normally use for semver version bumping, or do they do one of the two things I mentioned above?

**Comment by trevordmiller** [comment]
Another option, since Vim doesn't care about semver, is to always auto tag with `npm version minor` or something, but that feels dirty. Also, I'm looking for a solution I can use with my other packages.

**Comment by trevordmiller** [comment]
Asked on twitter:
https://twitter.com/trevordmiller/status/787048100380618752

**Comment by trevordmiller** [comment]
@designfrontier suggested option #2 from above, which I'm willing to do to remove the burden from contributors. Just means I can't merge stuff from my phone anymore 😆 
![image](https://cloud.githubusercontent.com/assets/5497885/19404148/fa03f7b2-9228-11e6-9d6d-000788500213.png)
