### ISSUE TITLE
Fix colors of the patch adding view

### ISSUE THREAD

**Issue by alexlafroscia** [trevordmiller/nova-vim#45]
In Fugitive you can stage particular patches, which is handy.  Nova must miss a few of the colors though, because things look a little... Rough.

<img width="531" alt="screen shot 2016-10-13 at 3 58 38 pm" src="https://cloud.githubusercontent.com/assets/1645881/19370020/f0aa94a8-915d-11e6-84c5-f2ce2706edd3.png">

I'll update the colors here so you can assign this to me.  Just wanted to make an issue to signal my intention to fix this.

**Comment by trevordmiller** [comment]
Ewww, yeah haha. Fugitive must not inherit from the other diff highlight groups. Sounds good. Thanks @alexlafroscia, you have been a great help :)

**Comment by trevordmiller** [comment]
@alexlafroscia I don't know if you are doing Hacktoberfest, but I've added the label so you can get a free shirt if you want :) https://hacktoberfest.digitalocean.com/

**Comment by alexlafroscia** [comment]
Absolutely, happy to help 😀 I'm used to trying to get all of my tools to use the same colors manually, and *love* that Nova provides Atom, Vim, Tmux, etc. from a single source that are all in sync. Gotta give back where I can, and I know Vimscript and JS so I'm able to.

**Comment by trevordmiller** [comment]
@alexlafroscia Thanks man. I was in the same boat 😆

**Comment by trevordmiller** [comment]
Hey @alexlafroscia were you still planning on doing this?

**Comment by trevordmiller** [comment]
Actually nevermind.
I'm closing this for now, since it is lower priority than other things I'm working on. If anyone would like to re-open the issue and submit a pull request, let me know! I'd be happy to have your contribution :)

**Comment by alexlafroscia** [comment]
Sorry, this slipped by me. I'll try to get to it... Eventually. Not sure when though, most of my OSS time is tied up elsewhere right now.

**Comment by trevordmiller** [comment]
@alexlafroscia No worries. Feel free to reopen if you get to it :)
