### ISSUE TITLE
Weird Tmux colors

### ISSUE THREAD

**Issue by jdsimcoe** [trevordmiller/nova-vim#53]
When using Vim from `tmux` I get some janky colors:

<img width="1362" alt="screen shot 2016-12-09 at 11 21 40 am" src="https://cloud.githubusercontent.com/assets/275617/21061556/c4a9e5d6-be01-11e6-9be1-ee756f10f6f3.png">

Any idea why this is?

**Comment by trevordmiller** [comment]
@jdsimcoe Did you follow the Tmux instructions from [the website instructions](http://www.trevordmiller.com/nova/)? My guess would be you are either on an old version of tmux or you aren't using the needed `.tmux.conf` pieces from the linked example.
![image](https://cloud.githubusercontent.com/assets/5497885/21061692/a002da72-be0a-11e6-8419-a07479476d22.png)

**Comment by jdsimcoe** [comment]
👍
