### ISSUE TITLE
termguicolors throwing error

### ISSUE THREAD

**Issue by PezCoder** [trevordmiller/nova-vim#56]
I am using VIM 7.3 & iTerm2 (both with the nova theme & plugin provided). I got this error when i first tried to launch vim after installing nova.

![image](https://cloud.githubusercontent.com/assets/8057916/21238557/7ba8d626-c329-11e6-95ea-e6f1ca6c42bd.png)

**Comment by trevordmiller** [comment]
See comments on https://github.com/trevordmiller/nova-vim/pull/57
