### ISSUE TITLE
hlsearch active element not highlighting 

### ISSUE THREAD

**Issue by alnjxn** [trevordmiller/nova-vim#61]
Got a weird issue. I if i use the /gc option on find and replace to confirm each replace, there is no highlighting of the active word. See example, where I show the correct behavior first with the default color scheme :

![mar-04-2017 13-55-38](https://cloud.githubusercontent.com/assets/1423708/23581487/cadcc5f8-00e2-11e7-9aa3-10d08682419f.gif)

Can someone reproduce?

**Comment by trevordmiller** [comment]
Hi @alnjxn, thank you for your feedback. This is a new feature request, so I will leave this issue open so that I can take care of it.

**Comment by trevordmiller** [comment]
@alnjxn I did some research and testing and the functionality of having a different search color on the active item is not built-in to vim; the default color scheme must be applying something to hack this to work in your example. The only two "highlight groups" (things you can control in a color scheme) are "Search" (after hitting enter, the highlighting if you have `set hlsearch` on) and "IncSearch" (highlighting while typing a search before hitting enter if you have `set incsearch` on).

Sorry about that. Looks like there is a plugin to give you this behavior though:
https://github.com/timakro/vim-searchant

More info if you are interested:
http://stackoverflow.com/questions/7198579/highlight-current-search-result-in-vim
https://superuser.com/questions/412125/vim-how-to-change-the-current-item-highlight-color-when-substituting

**Comment by trevordmiller** [comment]
I am going to upgrade the current search colors in the next release though to be more stark:
![image](https://cloud.githubusercontent.com/assets/5497885/24319391/0f5e4640-10e0-11e7-8a6c-c8edc3c54565.png)

^ after searching for `/const`

**Comment by trevordmiller** [comment]
I am improving the constrast of the Search + IncSearch styles though in the next release:
![image](https://cloud.githubusercontent.com/assets/5497885/24319409/890ba172-10e0-11e7-92f4-72f3621558a8.png)

^ searching for `/const`

**Comment by alnjxn** [comment]
@trevordmiller thanks for looking into this. Will def check out the plugins. Contrast in the new screen pics look great. Keep up all the good work!
