### ISSUE TITLE
Cursor line is not showing up in Vim

### ISSUE THREAD

**Issue by BrandonShega** [trevordmiller/nova-vim#62]
Hi! I love this theme, I got it for vim, tmux, iTerm, git and for some reason in vim my cursor line is not highlighting just the block cursor is.  Also my status line seems to be a different color and I'm not sure what I have done wrong :(

If you have any ideas I'd appreciate them.

Here is a screenshot of what vim look like for me:

![vim screenshot](https://cloud.githubusercontent.com/assets/1090748/23916763/a8258354-08c3-11e7-8b61-fd01c14a623e.png)

**Comment by trevordmiller** [comment]
@BrandonShega The colors shown in the screenshot are not Nova colors; it is also missing the default status line color. My guess is the plugin wasn't installed correctly, or an old version of Vim is installed (without true color support). What do you get when you run `vim --version` in your shell? You should get `8.0` or above. Have you gone through each of the steps and notes on  https://trevordmiller.com/projects/nova?

![image](https://cloud.githubusercontent.com/assets/5497885/23932800/647c852e-08f7-11e7-8852-262b3cbf75de.png)

**Comment by trevordmiller** [comment]
@BrandonShega Also, does running inside tmux look differently than outside of tmux? If so, tmux doesn't have the right config or is an old version without true color support. Please see the instructions on the website ^ for Tmux as well as Vim.

![image](https://cloud.githubusercontent.com/assets/5497885/23932881/dffb14d6-08f7-11e7-99c3-f2a12faad431.png)

**Comment by BrandonShega** [comment]
I thought the colors were looking a little off... I'll let you know what the output is tomorrow and redo the install as well.

**Comment by trevordmiller** [comment]
@BrandonShega Ok. My guess is you are either have an old version of Vim or Tmux or both. Vim should be `8.0.0`+ and tmux should be `2.2`+. If you are on a Mac, I recommend using Homebrew (ie `brew install vim && brew install tmux`) to get the latest of each. Then just make sure your `~/.vimrc` has:

```
{Plugin Manager} 'trevordmiller/nova-vim'
colorscheme nova
```

Example: https://github.com/trevordmiller/nova-vim/blob/master/assets/.vimrc

And your `.tmux.conf` has:

```

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g pane-border-style 'fg=brightblack,bg=black'
set -g pane-active-border-style 'fg=brightwhite,bg=black'
set -g status-style 'fg=brightblack,bg=black'
set -g message-style 'fg=cyan, bg=black'
set -g clock-mode-colour cyan
```

Example: https://github.com/trevordmiller/nova-tmux/blob/master/assets/.tmux.conf

It should look like the example screenshots here: https://trevordmiller.com/projects/nova

**Comment by trevordmiller** [comment]
Closing for now as I assume this will fix the problem, but feel free to reopen if it doesn't :) Thanks for using Nova.

**Comment by BrandonShega** [comment]
Hi @trevordmiller, ok so I have vim 8.0 with patches 1-456 installed via homebrew and tmux 2.3 installed via homebrew.  Vim looks the same installed both in and outside of tmux.  One thing I did notice and I think this was mentioned in another issue or a google post but if I don't have `set notermguicolors` at the bottom of  my `~/.vimrc` then all of the colors are just gone.

Here are links to my `.vimrc` and `.tmux.conf` if you'd like to take a look at them. (I actually use a predefined dotfile package so I have a .vimrc and .vimrc.local as well as .tmux.conf and .tmux.conf.local, I will link them both maybe there is something in the default prohibiting this)

vimrc: https://gist.github.com/BrandonShega/0777e48014354ac3fa9e71509ccf982b
vimrc.local: https://gist.github.com/BrandonShega/7935fc9fe3f12540ec34f5b0fe96c9f2
tmux.conf: https://gist.github.com/BrandonShega/f4e00bcbc6d0719a8960238c6f73c11b
tmux.conf.local: https://gist.github.com/BrandonShega/b3a2a882ff4fc9e0863e49c46ae5155e

I know there are probably some duplicate lines between the 2 versions, I'm still working on cleaning that up.  Let me know if you see anything that stands out though.

Thanks!

**Comment by BrandonShega** [comment]
Never mind I removed the nova-vim folder from my bundle folder and then reinstalled it and now it seems to be working ¯\_(ツ)_/¯.

**Comment by trevordmiller** [comment]
@BrandonShega Ok good glad you got it working :) Will close this issue. Hope it works well for you.
