### ISSUE TITLE
Unknown option: termguicolors

### ISSUE THREAD

**Issue by Xaeroxe** [trevordmiller/nova-vim#64]
I get the following error when I install this plugin and add `colorscheme nova` to my `.vimrc`.  I'm using the Janus vim distribution on Ubuntu 16.04
![unknown](https://cloud.githubusercontent.com/assets/6182002/24390041/698d061e-1343-11e7-9c47-f2d5c49c0a07.png)

**Comment by Xaeroxe** [comment]
I'm using GNOME Terminal version 3.18.3 as well.

**Comment by trevordmiller** [comment]
@Xaeroxe Thanks for using Nova. As mentioned [in the documentation](https://trevordmiller.com/projects/nova), "You'll need True Color support (latest Vim, Neovim, or GUI Vim)";

If you run `vim --version` it should be at least `8.0`:
![image](https://cloud.githubusercontent.com/assets/5497885/24414986/37b2de0c-139d-11e7-8301-41081f91e4eb.png)

So since you are on Ubuntu, I believe you will need to do this:
```
sudo apt-get update
sudo apt-get install vim
```

Hope this helps.

**Comment by trevordmiller** [comment]
Although I don't use Janus or know much about it, it may need to be updated to upgrade Vim. Either way, your Vim version needs to be latest for True Color support.

**Comment by Xaeroxe** [comment]
I thought of that, so I checked to see if my Vim had true color support using this

```
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```
And it did display correctly.  I am also able to use this vim color theme: http://vimcolors.com/626/spring-night/dark with the same setup.

**Comment by Xaeroxe** [comment]
However it did just occur to me that just because the terminal has true color support doesn't mean that Vim does.  I'll check that next time I'm at this box.

**Comment by trevordmiller** [comment]
@Xaeroxe That is correct, both your terminal and Vim itself need true color support - so along with your terminal which sounds like it is ok, you'll need to upgrade Vim to latest.

**Comment by Xaeroxe** [comment]
Ah, yes Ubuntu default vim doesn't have TrueColor support.  I got a version of Vim on my computer that does though and we're all good now.  Thanks for helping me, sorry for noob issue.

**Comment by trevordmiller** [comment]
@Xaeroxe No worries, glad you got it figured out :)
