### ISSUE TITLE
Any interest in providing translucence compatibility?

### ISSUE THREAD

**Issue by oblitum** [trevordmiller/nova-vim#70]
I've found this colorscheme quite awesome but [sometimes I like to set my background transparent](https://github.com/oblitum/dotfiles/blob/archlinux/.vimrc#L208-L211) and this theme doesn't play well with that tweak because it sets bg colors for several individual highlighting groups instead of just the fg colors. It's the first time translucence simply gets broken for me:

![screenshot from 2017-04-27 17-07-44](https://cloud.githubusercontent.com/assets/1269815/25502425/e4efb1a8-2b6c-11e7-9da5-bc825c86dd74.png)

Notice how comments for example have clear opaque background.

Translucence on true colors works well on NeoVim. [Vim needs a patch](https://github.com/vim/vim/issues/981#issuecomment-264643975) (for true colors).

Is of any interest to have the colorscheme playing well with translucence? No problems if it's a won't fix.

**Comment by trevordmiller** [comment]
@oblitum Thank you for posting an issue and for using Vim! I personally don't want to encourage translucence use with this theme as it is already a low contrast theme and translucence makes it ever lower contrast; I also purposefully put the background color overrides in places as the only way I could find to ensure consistency across multiple terminal types > vim types > tmux use. If you can find a way around this, I'd accept a PR, but for now I'd like to take a pass on this. Thanks again for your issue though and for trying it out :)

**Comment by oblitum** [comment]
@trevordmiller OK thanks. Regarding contrast I don't get because using transparency I generally get higher contrast, and this also happen here as the background is quite light and on translucence it gets darker, which gets more contrast with the text.

**Comment by trevordmiller** [comment]
@oblitum That can be true if you have a darker background, but when you have windows behind your terminal or a lighter background the contrast will be poor and I don't want to allow Nova to be used/recorded/presented with in those situations. Again if you want to PR or fork that's cool with me, but this would add some complexity and bugs and I haven't had anyone else request this as I don't think it is a very common thing :)

**Comment by oblitum** [comment]
@trevordmiller OK thanks. In this mode I generally just set terminal's background to the same color as the Vim colorscheme, and control alpha. I generally apply just a bit of alpha but in this screenshot I've applied more so that the issue turned more evident, otherwise it would be hard to see it.
