### ISSUE TITLE
How to enable iTerm2 truecolor—Colorscheme doesn't work with terminal ViM

### ISSUE THREAD

**Issue by jlconlin** [trevordmiller/nova-vim#71]
I can't get the color scheme to work in terminal vim. I believe that my problem lies in the fact that I don't have truecolor support in my terminal ViM; the color scheme works in MacViM, but not in the terminal.

I am using iTerm2 on a Mac with `tmux`. I have installed the tmux and iTerm2 color schemes as described on the website; those work just fine. You can see my ViM configuration [here](https://github.com/jlconlin/ViMConfig/blob/master/vimrc).

**Comment by jlconlin** [comment]
While the `colorscheme nova` command is not at the end of my `vimrc` file, when it was at the end, I had the same issue. 

When I have `colorscheme nova` in my `vimrc` file, there is no syntax highlighting at all, in any filetype when using terminal ViM. It works just fine with MacVim.

**Comment by trevordmiller** [comment]
@jlconlin: Thanks for trying out Nova! I use terminal Vim and tmux as well. Are you on latest iTerm + Vim 8 + tmux 2.5? Latest of each is required for the true color support :)

**Comment by trevordmiller** [comment]
Also, the `colorscheme nova` syntax is required in your .vimrc for the colorscheme to load.

**Comment by jlconlin** [comment]
Ah, I wasn't using tmux 2.5. Now that I've updated it, it appears to work fine; although it takes *much* longer for my files to open.

**Comment by trevordmiller** [comment]
@jlconlin Ok glad it's working for you. I'd recommend posting an issue on the tmux repo if you can narrow down the perf issue :)
