### ISSUE TITLE
Highlight XML namespace attributes as well.

### ISSUE THREAD

**Issue by MeanEYE** [trevordmiller/nova-vim#78]
Currently color scheme highlights XML namespace tags properly like this:
![image](https://user-images.githubusercontent.com/1911594/29416178-9dad1a1e-8365-11e7-87d6-ef894d86cce3.png)

However XML allows attributes to be part of namespace as well:
![image](https://user-images.githubusercontent.com/1911594/29416223-b91aa212-8365-11e7-815c-5d8ffadc018c.png)

As I am not sure if this is by design, I am reporting it just in case.

**Comment by trevordmiller** [comment]
@MeanEYE Thank you for using Nova and for your feedback! Native Vim XML highlight groups (the groups you can select to color) are fairly limited sadly so I don't have the control to color namespaces separately in attributes, sorry! But if you use a specific XML plugin that adds more granular highlight groups, we can add support. For example, here is one such rule for a plugin specific highlight group:
https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L176

Feel free to submit a pull request as well.

Thanks again!
