### ISSUE TITLE
What is the cleanest way to make the background a little darker?

### ISSUE THREAD

**Issue by airblade** [trevordmiller/nova-vim#79]
Hello!

Thank you for making and releasing this colour scheme.

I would quite like to make the background a little darker.  What's the cleanest way to do that?

Also, how can I find a darker version of the current background colour (instead of a random darker colour)?

Thanks!

**Comment by trevordmiller** [comment]
Hi @airblade, thanks for trying out Nova! If you are looking for higher contrast, honestly I'd recommend another theme as Nova isn't built for high contrast. But if you do just want to darken the background you would have to fork `nova-colors` and and `nova-vim` and replace the `uiGroups.background` color in all the instances like https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L14. As for a darker version of the current background color, there is `uiGroups.backgroundShade` which is quite a bit darker (used in the pane splits and status bars) or you could check out some color theory resources like this: https://graphicdesign.stackexchange.com/questions/75417/how-to-make-a-given-color-a-bit-darker-or-lighter. Hope this helps. Good luck.

**Comment by airblade** [comment]
The contrast is fine for me; I would just like to tweak the background a little.  I'll try it as you recommended.

Thanks @trevordmiller!
