### ISSUE TITLE
Clash with another plugin

### ISSUE THREAD

**Issue by emaniacs** [trevordmiller/nova-vim#80]
I love this project and thanks.

but when i use this plugin, another plugin ([vim-interestingwords](https://github.com/lfv89/vim-interestingwords) didn't work.

Is there any setting to make it work?

This is my vimrc https://github.com/emaniacs/my-dot-config/blob/master/dot-vimrc

Screenshoot with and without nova plugin. 
![vim-interestingwords-with-nova](https://user-images.githubusercontent.com/314789/30155092-25462eb2-93e6-11e7-87ff-252deabe4f58.png)
![vim-interestingwords-without-nova](https://user-images.githubusercontent.com/314789/30155091-25428456-93e6-11e7-8534-36132a9670e7.png)

**Comment by trevordmiller** [comment]
According to the interesting-words documentation, you need to add an array of colors to your vimrc which I don't see in your vimrc:

https://github.com/lfv89/vim-interestingwords#configuration

I'd recommend using [nova-colors](https://github.com/trevordmiller/nova-colors/blob/master/src/index.js#L1-L21) to stay consistent with `nova-vim` so for example:

```
let g:interestingWordsGUIColors = ['#A8CE93', '#83AFE5', '#9A93E1', '#D18EC2', ''#F2C38F', '#DADA93']
```

**Comment by emaniacs** [comment]
I was try the configurations, but still didn't work :(

**Comment by agarrharr** [comment]
@emaniacs I tried it and it works for me.

**Comment by emaniacs** [comment]
@agarrharr may i see your vimrc?

i dont know, everything is ok after i unset termguicolors, **set notermguicolors** but the brightness increased..

**Comment by emaniacs** [comment]
@agarrharr i try your [vimrc](https://raw.githubusercontent.com/agarrharr/settings/master/gnu%2Blinux/dotfiles/.vimrc) and its work

I gonna check my vimrc and gonna updated in this issue,,

Thanks :)

**Comment by emaniacs** [comment]
I use old repository https://github.com/vasconcelloslf/vim-interestingwords which redirected to https://github.com/lfv89/vim-interestingwords in my vimrc.
its fixed when i use new repository url in my vim. :)
