### ISSUE TITLE
Don't override user's vertical separator char

### ISSUE THREAD

**Issue by cronokun** [trevordmiller/nova-vim#88]
It's very confusing when a color scheme overrides user's GUI settings, like `set fillchars+=vert:│`.
I personally prefer BOX DRAWINGS HEAVY VERTICAL (`┃`).

**Comment by trevordmiller** [comment]
@cronokun Thanks for using Nova and for the feedback. Feel free to submit a pull request, otherwise I'll get to this :)

**Comment by trevordmiller** [comment]
@cronokun This was released in https://github.com/trevordmiller/nova-vim/releases/tag/v3.15.0. Please upgrade and let me know if you have any problems. Thanks!

**Comment by cronokun** [comment]
@trevordmiller Thanks! And thanks for awesome color scheme! 👍
