### ISSUE TITLE
Can't see ColorCoumn

### ISSUE THREAD

**Issue by stsewd** [trevordmiller/nova-vim#91]
Hi, I notice that the color for `ColorColumn` is not visible. I'm using the latest Neovim.

![colocolumn](https://user-images.githubusercontent.com/4975310/36005703-da72d300-0d06-11e8-955d-d7911710fe02.png)

Manually setting `hi ColorColumn guibg=#556873` solve this.

**Comment by trevordmiller** [comment]
@stsewd Thanks for using Nova! As shown in your screenshot, colorcolumn is set and visible - it is just very low contrast: 
![image](https://user-images.githubusercontent.com/5497885/36042555-7326bfda-0d89-11e8-9fd1-8e6d286929cd.png)

I prefer it this way, but feel free to override it in your own settings as you have done :)

**Comment by stsewd** [comment]
@trevordmiller well, actually I don't see it at all on my screen

![colorcolumn1](https://user-images.githubusercontent.com/4975310/36047294-a005c0f8-0da9-11e8-8786-7ea9897bbcc6.png)

![colorcolumn2](https://user-images.githubusercontent.com/4975310/36047292-9fe3cf7a-0da9-11e8-813a-8b340f5d09fd.png)

**Comment by trevordmiller** [comment]
@stsewd Ok thanks for the screenshots - I'll look into it!

**Comment by stsewd** [comment]
@trevordmiller Thanks! Very appreciated!

**Comment by trevordmiller** [comment]
@stsewd You were right, this was a bug. It has been fixed and released in https://github.com/trevordmiller/nova-vim/releases/tag/v3.17.0. Please update your `nova-vim` plugin and let me know if it works ok for you :) Thanks for using Nova and for the feedback!

**Comment by stsewd** [comment]
@trevordmiller works perfectly, thanks for your time!
