### ISSUE TITLE
Nova colors for alacritty

### ISSUE THREAD

**Issue by leonardt** [trevordmiller/nova-vim#98]
Haven't put too much effort into the repository, but it's there for anyone who wants the basic color template for Alacritty (https://github.com/jwilm/alacritty)

@trevordmiller I've added you as a collaborator so feel free to spruce it up or just migrate the contents to entirely different repo, it doesn't matter to me. Feel free to close this issue once you've read it since it's not really an issue.

**Comment by leonardt** [comment]
Forgot to include a link to the repository! https://github.com/leonardt/nova-alacritty

**Comment by trevordmiller** [comment]
Thanks @leonardt! I'll leave this issue open so I can add this to the "Community plugins" section of https://trevordmiller.com/projects/nova.

**Comment by trevordmiller** [comment]
@leonardt I've added your Nova Alacritty plugin to the "Community plugins" section of https://trevordmiller.com/projects/nova. The only thing that is missing is the repo needs an example screenshot located at `https://github.com/leonardt/nova-alacritty/assets/screenshot.png` to match the other Nova plugins. Would you mind adding that so the website no longer has a broken link?

![image](https://user-images.githubusercontent.com/5497885/38772603-3e416206-3ff8-11e8-9918-d458cfe8ce4c.png)

Also, once https://github.com/jwilm/alacritty/issues/285#issuecomment-381361600 gets a response, I'll update the generic terminal icon to the official new Alacritty logo on the Nova website.

**Comment by trevordmiller** [comment]
@leonardt Does that make sense? Let me know when you have added the file to `https://github.com/leonardt/nova-alacritty/assets/screenshot.png` and I'll close this issue. Thanks!

**Comment by leonardt** [comment]
Done! Thanks for the reminder

**Comment by megalithic** [comment]
hah, weird, so i added the colors to the alacritty wiki not too long ago. didn't even think to check back here.

**Comment by leonardt** [comment]
i noticed that later after I had made this repository!

**Comment by trevordmiller** [comment]
@megalithic @leonardt So should I change anything for the current "Alacritty" section of the Nova website here: https://trevordmiller.com/projects/nova?

![image](https://user-images.githubusercontent.com/5497885/40143994-476169cc-591a-11e8-9d33-45c772ee03db.png)

**Comment by megalithic** [comment]
@trevordmiller @leonardt that looks good to me sir!
